### ISSUE TITLE
功能需要，带背景图的，合成base64图片

### ISSUE THREAD

**Issue by jiudan** [peng20017/wx-drop#1]
是一种DIY功能。一张背景，多个图标，多个文本 合成一张图

**Comment by jiudan** [comment]
主要是图片旋转，缩放之后 ， 合成的图片位置

**Comment by jiudan** [comment]
var ctx = wx.createCanvasContext('firstCanvas');

_this.data.itemList.forEach(function(v,i){
			  console.log(v); 
				//ctx.beginPath();
				ctx.save();
				ctx.translate(v.x, v.y);
				ctx.rotate(v.rotate*Math.PI/180);
				ctx.scale(v.scale,v.scale);
				ctx.translate(-v.x, -v.y);
				ctx.drawImage(v.image, v.left, v.top, v.width, v.height);
				ctx.restore();  
		 });
ctx.draw();

---------------------------------------------------------------

canvas转base64 ，用upng
https://github.com/AleynP/cxc-base64/tree/master/pages/cardscanner/upng-js


var upng = require('../../utils/upng-js/UPNG.js'); //调用模块
ctx.draw(false, () => {
				// 2. 获取图像数据
				wx.canvasGetImageData({
					canvasId: 'firstCanvas',
					x: 0,
					y: 0,
					width: 400,
					height: 200,
					success(res) {
						// 3. png编码
						let pngData = upng.encode([res.data.buffer], res.width, res.height)
						// 4. base64编码
						let base64 = wx.arrayBufferToBase64(pngData)
						//console.log(base64);
						//data:image/jpg;base64,
						_this.setData({resultPic:"data:image/jpg;base64,"+base64});
					}
				})
			})

**Comment by peng20017** [comment]
来晚了，功能已添加

**Comment by jiudan** [comment]
感谢你写的插件，当初弄的时候，发现多个图片 合成 一张base64，发现提交ajax有bug，需要用到&nbsp;wx.getImageInfo() 和 wx.canvasToTempFilePath()






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pishangtian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 下午4:01
收件人:&nbsp;"peng20017/wx-drop"<wx-drop@noreply.github.com&gt;;
抄送:&nbsp;"难得聪明"<1095680703@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [peng20017/wx-drop] 功能需要，带背景图的，合成base64图片 (#1)




来晚了，功能已添加

**Comment by jiudan** [comment]
漏发的插件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pishangtian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 下午4:01
收件人:&nbsp;"peng20017/wx-drop"<wx-drop@noreply.github.com&gt;;
抄送:&nbsp;"难得聪明"<1095680703@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [peng20017/wx-drop] 功能需要，带背景图的，合成base64图片 (#1)




来晚了，功能已添加

**Comment by peng20017** [comment]
确实是被我漏发了。。

**Comment by jiudan** [comment]
在GitHub上我说的，有问题的。我发附件的那个demo，没太大问题，我已经上线了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pishangtian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 下午4:47
收件人:&nbsp;"peng20017/wx-drop"<wx-drop@noreply.github.com&gt;;
抄送:&nbsp;"难得聪明"<1095680703@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [peng20017/wx-drop] 功能需要，带背景图的，合成base64图片 (#1)




确实是被我漏发了。。
